export const REQUEST_REGISTER = "REQUEST_REGISTER";
export const SUCCESS_REGISTER = "SUCCESS_REGISTER";
export const FAIL_REGISTER = "FAIL_REGISTER";
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAIL_LOGIN = "FAIL_LOGIN"; 
export const CLEAR_ERROR = "CLEAR_ERROR"