export const REQUEST_GET_PRODUCTS = "REQUEST_GET_PRODUCTS";
export const SUCCESS_GET_PRODUCTS = "SUCCESS_GET_PRODUCTS";
export const FAIL_GET_PRODUCTS = 'FAIL_GET_PRODUCTS';
export const REQUEST_GET_PRODUCT = "REQUEST_GET_PRODUCT";
export const SUCCESS_GET_PRODUCT = "SUCCESS_GET_PRODUCT";
export const FAIL_GET_PRODUCT = 'FAIL_GET_PRODUCT';